- name: BASE > Install PHP packages
  shell: amazon-linux-extras enable php7.4
  become: yes

- name: Install Remi Repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  become: yes
  # warn: false

- name: Enable Remi for php-{{ php_version }}
  shell: yum-config-manager --enable remi-php74
  become: yes
  # warn: false

- name: PHP-FPM > Install PHP-FPM {{ php_version }} for Amazon linux
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ php_packages_amazon }}"
  become: yes

- name: PHP-FPM > Create path project
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0775
  loop:
    - "{{ app_path_project }}"
    - "{{ app_path_project }}/shared"
  become: yes

- name: PHP-FPM > Install Composer
  shell: |
    curl -s https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer
  become: yes

- name: PHP-FPM > Install Deployer
  shell: |
    curl -LO https://deployer.org/deployer.phar
    mv deployer.phar /usr/local/bin/dep
    chmod +x /usr/local/bin/dep
  become: yes

- name: PHP-FPM > Change user/group pool
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^user =(.*)$"
      line: "user = {{ deploy_user }}"
    - regexp: "^group =(.*)$"
      line: "group = {{ deploy_user }}"
    - regexp: "^listen.owner =(.*)$"
      line: "listen.owner = {{ deploy_user }}"
    - regexp: "^listen.group =(.*)$"
      line: "listen.group = {{ deploy_user }}"
    - regexp: "^;(listen.mode = 0660)"
      line: "listen.mode = 0660"
  become: yes

- name: PHP-FPM > Modifier pool.d/www/conf
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - regexp: '^;(php_flag\[display_errors\] = off)'
      line: "php_flag[display_errors] = off"
    - regexp: '^;(php_admin_value\[error_log\] = \/var\/log\/fpm-php.www.log)'
      line: "php_admin_value[error_log] = /var/log/fpm-php.www.log"
    - regexp: '^;(php_admin_flag\[log_errors\] = on)'
      line: "php_admin_flag[log_errors] = on"
    - regexp: ';(php_admin_value\[memory_limit\] = (.*)$)'
      line: "php_admin_value[memory_limit] = 128M"
  become: yes

- name: PHP-FPM > Restart PHP-FPM after modifier
  service:
    name: php-fpm
    state: restarted
  become: yes
