# Detect RUBY patch
- name: 1. RAILS-WITH-RVM > Detect installed RUBY patch number
  shell: >
    {{ rvm_rvm }} list strings | grep {{ item }} | tail -n 1
  loop: "{{ rvm_rubies }}"
  changed_when: False
  register: ruby_patch
  check_mode: no # Run in normal mode when in --check mode (http://docs.ansible.com/ansible/playbooks_checkmode.html)
  become_user: "{{ deploy_user }}"
  become: yes
- debug: msg="{{ item.stdout_lines | default([]) }}"
  loop: "{{ ruby_patch.results }}"



# Install Rails
- name: 1. RAILS-WITH-RVM > Install rails {{ rails_version }}
  shell: "{{ rvm_install_path }}/wrappers/{{ item.stdout }}/gem install rails -v '{{ rails_version }}'"
  loop: "{{ ruby_patch.results }}"
  register: rails_install
  become_user: "{{ deploy_user }}"
  become: yes
- debug: var=rails_install.results
