- hosts: tag_Role_ruby

  become_method: sudo
  gather_facts: yes

  # pre_tasks:
  #   - name: Check OS distribution condition
  #     debug:
  #       var: "{{ item }}"
  #     loop:
  #       - ansible_distribution
  #       - ansible_distribution_version
  #     failed_when:
  #       - ansible_distribution != 'Ubuntu' or ansible_distribution_version != '20.04'

  roles:
    - base
    - aws-cli
    - hostname
    - distribute-key
    - ruby-with-rvm
    - rails-with-rvm
    - puma-with-rvm
    - sidekiq-with-rvm
    - nginx
    - redis
    - npm-ppa
    - yarn-ppa
    - mysql-server
    - mysql-client
    - logrotate
