- name: MYSQL > Instal MySQL
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ base_mysql_packet }}"
  become: yes

- name: MYSQL > Create folder conf.d if it not exist
  file:
    path: "{{ mysql_conf_dir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: "0755"
  become: yes

- name: MYSQL > Create log folder
  file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: "0755"
  become: yes

- name: MYSQL > Create datadir if it not exist
  file:
    path: "{{ mysql_data_dir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: "0755"
  become: yes

- name: MYSQL > Get MySQL version
  shell: "mysql --version"
  register: mysql_cli_version
  changed_when: false
  check_mode: false
- debug: var=mysql_cli_version.stdout_lines

- name: MYSQL > Update file my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: "0644"
    force: "{{ overwrite_global_mycnf }}"
  become: yes

- name: MYSQL > Restart service
  service:
    name: mysql
    state: restarted
  become: yes

- name: MYSQL > Create Database for Application
  mysql_db:
    name: "{{ APP_DB_NAME }}"
    state: present
  become: yes

- name: MYSQL > Add user for Database Application
  mysql_user:
    name: "{{ APP_DB_USER }}"
    password: "{{ APP_DB_PASSWORD }}"
    priv: "{{ APP_DB_NAME }}.*:ALL"
    state: present
  no_log: true
  become: yes
