env: dev
full_env: development

# Basic Authen for NGINX
BASIC_AUTH_USERNAME: ""
BASIC_AUTH_PASSWORD: ""

# Database Name, User & Password
APP_DB_NAME: "demo"
APP_DB_USER: "demo"
APP_DB_PASSWORD: "Demo123@"
