base_packages_amazon:
  - tcl-devel
  - gettext
  - openssl
  - python3-pip
  - make
  - wget
  - unzip
  - logrotate
  - readline-devel
  - ncurses-devel
  - libxml2-devel
  - libxslt-devel
  - libcurl-devel
  - expat-devel
  - zlib-devel
  - openssl-devel
  - libffi-devel
  - libyaml-devel
  - sqlite-devel
  - sqlite
  - yum-utils
  - curl
  - vim-enhanced
  - git
  - acl

base_packages_ubuntu:
  - tcl-dev
  - gettext
  - fail2ban
  - openssl
  - python3-pip
  - make
  - wget
  - unzip
  - logrotate
  - zlib1g-dev
  - libssl-dev
  - libreadline6-dev
  - libncurses5-dev
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - libexpat1-dev
  - libz-dev
  - libssl-dev
  - libffi-dev
  - libyaml-dev
  - libsqlite3-dev
  - sqlite3
  - software-properties-common
  - build-essential
  - socat
  - apt-transport-https
  - curl
  - vim
  - git
  - acl
