php_packages:
  - php{{ php_version }}
  - php{{ php_version }}-bcmath
  - php{{ php_version }}-bz2
  - php{{ php_version }}-cgi
  - php{{ php_version }}-cli
  - php{{ php_version }}-common
  - php{{ php_version }}-curl
  - php{{ php_version }}-dba
  - php{{ php_version }}-dev
  - php{{ php_version }}-enchant
  - php{{ php_version }}-fpm
  - php{{ php_version }}-gd
  - php{{ php_version }}-gmp
  - php{{ php_version }}-imap
  - php{{ php_version }}-interbase
  - php{{ php_version }}-intl
  - php{{ php_version }}-json
  - php{{ php_version }}-ldap
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-mysql
  - php{{ php_version }}-odbc
  - php{{ php_version }}-opcache
  - php{{ php_version }}-pgsql
  - php{{ php_version }}-phpdbg
  - php{{ php_version }}-pspell
  - php{{ php_version }}-readline
  # - php{{ php_version }}-recode
  - php{{ php_version }}-snmp
  - php{{ php_version }}-soap
  - php{{ php_version }}-sqlite3
  - php{{ php_version }}-sybase
  - php{{ php_version }}-tidy
  - php{{ php_version }}-xml
  - php{{ php_version }}-xmlrpc
  - php{{ php_version }}-xsl
  - php{{ php_version }}-zip

php_packages_amazon:
  - php
  - php-bcmath
  - php-bz2
  - php-cgi
  - php-cli
  - php-common
  - php-curl
  - php-dba
  - php-devel
  - php-enchant
  - php-fpm
  - php-gd
  - php-gmp
  - php-odbc
  - php-pdo
  - php-intl
  - php-json
  - php-ldap
  - php-mbstring
  - php-opcache
  - php-pgsql
  - php-pspell
  - php-readline
  - php-snmp
  - php-soap
  - php-sqlite3
  - php-xml
  - php-xmlrpc
  - php-xsl
  - php-zip
  - php-mysqlnd
  # - php-pdo_dblib
  # - php-tidy
  # - php-imap #l敲들
  # - php-interbase #l敲들
  # - php-mysql #l敲들
  # - php-phpdbg #l敲들
