# - name: BASE > Install aptitude
#   apt:
#     name: aptitude
#     state: present
#   become: yes

- name: BASE > Add the {{ deploy_user }} user
  user:
    name: "{{ deploy_user }}"
    groups: adm,sudo
    state: present
    shell: /bin/bash
    append: yes
    createhome: yes
    home: /home/{{ deploy_user }}
  become: yes

- name: BASE > Install base packages
  apt:
    name: fail2ban
    state: latest
    update_cache: yes
  become: yes

- name: BASE > Install base packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ base_packages_ubuntu }}"
  become: yes

- name: BASE > Install chrony service
  apt:
    name: chrony
    state: present
  become: yes

- name: BASE > Enable chrony service
  service:
    name: chrony
    state: started
    enabled: yes
  become: yes

- name: BASE > Check status service chrony
  command: systemctl status chrony
  register: chrony_status
- debug: var=chrony_status.stdout_lines
